/*
 * Datamart Customer Relationship Management
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.Runtime.Serialization;
using System.Text;
using System.Text.Json;

namespace Itau.Cl.RF.CustomerRelationshipMgmnt.Bff.API.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class BalanceRating : IEquatable<BalanceRating>
    {
        /// <summary>
        /// Gets or Sets CommentCommercialInfoRating
        /// </summary>

        [DataMember(Name = "commentCommercialInfoRating")]
        public string CommentCommercialInfoRating { get; set; }

        /// <summary>
        /// Gets or Sets ValueRating
        /// </summary>

        [DataMember(Name = "valueRating")]
        public long? ValueRating { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BalanceRating {\n");
            sb.Append("  CommentCommercialInfoRating: ").Append(CommentCommercialInfoRating).Append("\n");
            sb.Append("  ValueRating: ").Append(ValueRating).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonSerializer.Serialize(this);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((BalanceRating)obj);
        }

        /// <summary>
        /// Returns true if BalanceRating instances are equal
        /// </summary>
        /// <param name="other">Instance of BalanceRating to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BalanceRating other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    CommentCommercialInfoRating == other.CommentCommercialInfoRating ||
                    CommentCommercialInfoRating != null &&
                    CommentCommercialInfoRating.Equals(other.CommentCommercialInfoRating)
                ) &&
                (
                    ValueRating == other.ValueRating ||
                    ValueRating != null &&
                    ValueRating.Equals(other.ValueRating)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (CommentCommercialInfoRating != null)
                    hashCode = hashCode * 59 + CommentCommercialInfoRating.GetHashCode();
                if (ValueRating != null)
                    hashCode = hashCode * 59 + ValueRating.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(BalanceRating left, BalanceRating right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(BalanceRating left, BalanceRating right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
