/*
 * Datamart Customer Relationship Management
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.Runtime.Serialization;
using System.Text;
using System.Text.Json;


namespace Itau.Cl.RF.CustomerRelationshipMgmnt.Bff.API.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class FinesNotPay : IEquatable<FinesNotPay>
    {
        /// <summary>
        /// Gets or Sets DateFinesNotPay
        /// </summary>

        [DataMember(Name = "dateFinesNotPay")]
        public long? DateFinesNotPay { get; set; }

        /// <summary>
        /// Gets or Sets Fines
        /// </summary>

        [DataMember(Name = "fines")]
        public List<FineNotPay> Fines { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FinesNotPay {\n");
            sb.Append("  DateFinesNotPay: ").Append(DateFinesNotPay).Append("\n");
            sb.Append("  Fines: ").Append(Fines).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonSerializer.Serialize(this);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((FinesNotPay)obj);
        }

        /// <summary>
        /// Returns true if FinesNotPay instances are equal
        /// </summary>
        /// <param name="other">Instance of FinesNotPay to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FinesNotPay other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    DateFinesNotPay == other.DateFinesNotPay ||
                    DateFinesNotPay != null &&
                    DateFinesNotPay.Equals(other.DateFinesNotPay)
                ) &&
                (
                    Fines == other.Fines ||
                    Fines != null &&
                    Fines.SequenceEqual(other.Fines)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (DateFinesNotPay != null)
                    hashCode = hashCode * 59 + DateFinesNotPay.GetHashCode();
                if (Fines != null)
                    hashCode = hashCode * 59 + Fines.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(FinesNotPay left, FinesNotPay right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(FinesNotPay left, FinesNotPay right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
