/*
 * Datamart Customer Relationship Management
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.Runtime.Serialization;
using System.Text;
using System.Text.Json;


namespace Itau.Cl.RF.CustomerRelationshipMgmnt.Bff.API.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class Participation : IEquatable<Participation>
    {
        /// <summary>
        /// Gets or Sets NameCorporateParticipations
        /// </summary>

        [DataMember(Name = "nameCorporateParticipations")]
        public string NameCorporateParticipations { get; set; }

        /// <summary>
        /// Gets or Sets ClientIdParticipations
        /// </summary>

        [DataMember(Name = "clientIdParticipations")]
        public long? ClientIdParticipations { get; set; }

        /// <summary>
        /// Gets or Sets DateParticipations
        /// </summary>

        [DataMember(Name = "dateParticipations")]
        public long? DateParticipations { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Participation {\n");
            sb.Append("  NameCorporateParticipations: ").Append(NameCorporateParticipations).Append("\n");
            sb.Append("  ClientIdParticipations: ").Append(ClientIdParticipations).Append("\n");
            sb.Append("  DateParticipations: ").Append(DateParticipations).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonSerializer.Serialize(this);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((Participation)obj);
        }

        /// <summary>
        /// Returns true if Participation instances are equal
        /// </summary>
        /// <param name="other">Instance of Participation to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Participation other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    NameCorporateParticipations == other.NameCorporateParticipations ||
                    NameCorporateParticipations != null &&
                    NameCorporateParticipations.Equals(other.NameCorporateParticipations)
                ) &&
                (
                    ClientIdParticipations == other.ClientIdParticipations ||
                    ClientIdParticipations != null &&
                    ClientIdParticipations.Equals(other.ClientIdParticipations)
                ) &&
                (
                    DateParticipations == other.DateParticipations ||
                    DateParticipations != null &&
                    DateParticipations.Equals(other.DateParticipations)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (NameCorporateParticipations != null)
                    hashCode = hashCode * 59 + NameCorporateParticipations.GetHashCode();
                if (ClientIdParticipations != null)
                    hashCode = hashCode * 59 + ClientIdParticipations.GetHashCode();
                if (DateParticipations != null)
                    hashCode = hashCode * 59 + DateParticipations.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(Participation left, Participation right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(Participation left, Participation right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
