/*
 * Datamart Customer Relationship Management
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.Runtime.Serialization;
using System.Text;
using System.Text.Json;


namespace Itau.Cl.RF.CustomerRelationshipMgmnt.Bff.API.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class QuotasContributions : IEquatable<QuotasContributions>
    {
        /// <summary>
        /// Gets or Sets DateQuotasContributions
        /// </summary>

        [DataMember(Name = "dateQuotasContributions")]
        public long? DateQuotasContributions { get; set; }

        /// <summary>
        /// Gets or Sets Quotas
        /// </summary>

        [DataMember(Name = "quotas")]
        public List<QuotaContributions> Quotas { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class QuotasContributions {\n");
            sb.Append("  DateQuotasContributions: ").Append(DateQuotasContributions).Append("\n");
            sb.Append("  Quotas: ").Append(Quotas).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonSerializer.Serialize(this);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((QuotasContributions)obj);
        }

        /// <summary>
        /// Returns true if QuotasContributions instances are equal
        /// </summary>
        /// <param name="other">Instance of QuotasContributions to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(QuotasContributions other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    DateQuotasContributions == other.DateQuotasContributions ||
                    DateQuotasContributions != null &&
                    DateQuotasContributions.Equals(other.DateQuotasContributions)
                ) &&
                (
                    Quotas == other.Quotas ||
                    Quotas != null &&
                    Quotas.SequenceEqual(other.Quotas)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (DateQuotasContributions != null)
                    hashCode = hashCode * 59 + DateQuotasContributions.GetHashCode();
                if (Quotas != null)
                    hashCode = hashCode * 59 + Quotas.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(QuotasContributions left, QuotasContributions right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(QuotasContributions left, QuotasContributions right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
