/*
 * Datamart Customer Relationship Management
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.Runtime.Serialization;
using System.Text;
using System.Text.Json;


namespace Itau.Cl.RF.CustomerRelationshipMgmnt.Bff.API.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class SiiSubEconomicSector : IEquatable<SiiSubEconomicSector>
    {
        /// <summary>
        /// Gets or Sets CommentEconomicSector
        /// </summary>

        [DataMember(Name = "commentEconomicSector")]
        public string CommentEconomicSector { get; set; }

        /// <summary>
        /// Gets or Sets EconomicSector
        /// </summary>

        [DataMember(Name = "economicSector")]
        public SiiEconomicSector EconomicSector { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SiiSubEconomicSector {\n");
            sb.Append("  CommentEconomicSector: ").Append(CommentEconomicSector).Append("\n");
            sb.Append("  EconomicSector: ").Append(EconomicSector).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonSerializer.Serialize(this);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((SiiSubEconomicSector)obj);
        }

        /// <summary>
        /// Returns true if SiiSubEconomicSector instances are equal
        /// </summary>
        /// <param name="other">Instance of SiiSubEconomicSector to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SiiSubEconomicSector other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    CommentEconomicSector == other.CommentEconomicSector ||
                    CommentEconomicSector != null &&
                    CommentEconomicSector.Equals(other.CommentEconomicSector)
                ) &&
                (
                    EconomicSector == other.EconomicSector ||
                    EconomicSector != null &&
                    EconomicSector.Equals(other.EconomicSector)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (CommentEconomicSector != null)
                    hashCode = hashCode * 59 + CommentEconomicSector.GetHashCode();
                if (EconomicSector != null)
                    hashCode = hashCode * 59 + EconomicSector.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(SiiSubEconomicSector left, SiiSubEconomicSector right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(SiiSubEconomicSector left, SiiSubEconomicSector right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
