/*
 * Datamart Customer Relationship Management
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.Runtime.Serialization;
using System.Text;
using System.Text.Json;


namespace Itau.Cl.RF.CustomerRelationshipMgmnt.Bff.API.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class StampedDocument : IEquatable<StampedDocument>
    {
        /// <summary>
        /// Gets or Sets CommentStampedDocuments
        /// </summary>

        [DataMember(Name = "commentStampedDocuments")]
        public string CommentStampedDocuments { get; set; }

        /// <summary>
        /// Gets or Sets Period
        /// </summary>

        [DataMember(Name = "period")]
        public int? Period { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class StampedDocument {\n");
            sb.Append("  CommentStampedDocuments: ").Append(CommentStampedDocuments).Append("\n");
            sb.Append("  Period: ").Append(Period).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonSerializer.Serialize(this);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((StampedDocument)obj);
        }

        /// <summary>
        /// Returns true if StampedDocument instances are equal
        /// </summary>
        /// <param name="other">Instance of StampedDocument to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(StampedDocument other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    CommentStampedDocuments == other.CommentStampedDocuments ||
                    CommentStampedDocuments != null &&
                    CommentStampedDocuments.Equals(other.CommentStampedDocuments)
                ) &&
                (
                    Period == other.Period ||
                    Period != null &&
                    Period.Equals(other.Period)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (CommentStampedDocuments != null)
                    hashCode = hashCode * 59 + CommentStampedDocuments.GetHashCode();
                if (Period != null)
                    hashCode = hashCode * 59 + Period.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(StampedDocument left, StampedDocument right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(StampedDocument left, StampedDocument right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
