/*
 * Datamart Customer Relationship Management
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.Runtime.Serialization;
using System.Text;
using System.Text.Json;


namespace Itau.Cl.RF.CustomerRelationshipMgmnt.Bff.API.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class StatusSituationPartner : IEquatable<StatusSituationPartner>
    {
        /// <summary>
        /// Gets or Sets NameCorporatePartners
        /// </summary>

        [DataMember(Name = "nameCorporatePartners")]
        public string NameCorporatePartners { get; set; }

        /// <summary>
        /// Gets or Sets ClientIdPartners
        /// </summary>

        [DataMember(Name = "clientIdPartners")]
        public long? ClientIdPartners { get; set; }

        /// <summary>
        /// Gets or Sets DatePartners
        /// </summary>

        [DataMember(Name = "datePartners")]
        public long? DatePartners { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class StatusSituationPartner {\n");
            sb.Append("  NameCorporatePartners: ").Append(NameCorporatePartners).Append("\n");
            sb.Append("  ClientIdPartners: ").Append(ClientIdPartners).Append("\n");
            sb.Append("  DatePartners: ").Append(DatePartners).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonSerializer.Serialize(this);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((StatusSituationPartner)obj);
        }

        /// <summary>
        /// Returns true if StatusSituationPartner instances are equal
        /// </summary>
        /// <param name="other">Instance of StatusSituationPartner to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(StatusSituationPartner other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    NameCorporatePartners == other.NameCorporatePartners ||
                    NameCorporatePartners != null &&
                    NameCorporatePartners.Equals(other.NameCorporatePartners)
                ) &&
                (
                    ClientIdPartners == other.ClientIdPartners ||
                    ClientIdPartners != null &&
                    ClientIdPartners.Equals(other.ClientIdPartners)
                ) &&
                (
                    DatePartners == other.DatePartners ||
                    DatePartners != null &&
                    DatePartners.Equals(other.DatePartners)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (NameCorporatePartners != null)
                    hashCode = hashCode * 59 + NameCorporatePartners.GetHashCode();
                if (ClientIdPartners != null)
                    hashCode = hashCode * 59 + ClientIdPartners.GetHashCode();
                if (DatePartners != null)
                    hashCode = hashCode * 59 + DatePartners.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(StatusSituationPartner left, StatusSituationPartner right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(StatusSituationPartner left, StatusSituationPartner right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
