/*
 * Datamart Customer Relationship Management
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.Runtime.Serialization;
using System.Text;
using System.Text.Json;


namespace Itau.Cl.RF.CustomerRelationshipMgmnt.Bff.API.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class TagInfractions : IEquatable<TagInfractions>
    {
        /// <summary>
        /// Gets or Sets DateTagInfractions
        /// </summary>

        [DataMember(Name = "dateTagInfractions")]
        public long? DateTagInfractions { get; set; }

        /// <summary>
        /// Gets or Sets Infractions
        /// </summary>

        [DataMember(Name = "infractions")]
        public List<Infraction> Infractions { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TagInfractions {\n");
            sb.Append("  DateTagInfractions: ").Append(DateTagInfractions).Append("\n");
            sb.Append("  Infractions: ").Append(Infractions).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonSerializer.Serialize(this);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((TagInfractions)obj);
        }

        /// <summary>
        /// Returns true if TagInfractions instances are equal
        /// </summary>
        /// <param name="other">Instance of TagInfractions to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TagInfractions other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    DateTagInfractions == other.DateTagInfractions ||
                    DateTagInfractions != null &&
                    DateTagInfractions.Equals(other.DateTagInfractions)
                ) &&
                (
                    Infractions == other.Infractions ||
                    Infractions != null &&
                    Infractions.SequenceEqual(other.Infractions)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (DateTagInfractions != null)
                    hashCode = hashCode * 59 + DateTagInfractions.GetHashCode();
                if (Infractions != null)
                    hashCode = hashCode * 59 + Infractions.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(TagInfractions left, TagInfractions right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(TagInfractions left, TagInfractions right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
