/*
 * Datamart Customer Relationship Management
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.Runtime.Serialization;
using System.Text;
using System.Text.Json;


namespace Itau.Cl.RF.CustomerRelationshipMgmnt.Bff.API.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class TagInformation : IEquatable<TagInformation>
    {
        /// <summary>
        /// Gets or Sets Serie
        /// </summary>

        [DataMember(Name = "serie")]
        public string Serie { get; set; }

        /// <summary>
        /// Gets or Sets Concessionaire
        /// </summary>

        [DataMember(Name = "concessionaire")]
        public string Concessionaire { get; set; }

        /// <summary>
        /// Gets or Sets InstallDate
        /// </summary>

        [DataMember(Name = "installDate")]
        public long? InstallDate { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TagInformation {\n");
            sb.Append("  Serie: ").Append(Serie).Append("\n");
            sb.Append("  Concessionaire: ").Append(Concessionaire).Append("\n");
            sb.Append("  InstallDate: ").Append(InstallDate).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonSerializer.Serialize(this);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((TagInformation)obj);
        }

        /// <summary>
        /// Returns true if TagInformation instances are equal
        /// </summary>
        /// <param name="other">Instance of TagInformation to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TagInformation other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    Serie == other.Serie ||
                    Serie != null &&
                    Serie.Equals(other.Serie)
                ) &&
                (
                    Concessionaire == other.Concessionaire ||
                    Concessionaire != null &&
                    Concessionaire.Equals(other.Concessionaire)
                ) &&
                (
                    InstallDate == other.InstallDate ||
                    InstallDate != null &&
                    InstallDate.Equals(other.InstallDate)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (Serie != null)
                    hashCode = hashCode * 59 + Serie.GetHashCode();
                if (Concessionaire != null)
                    hashCode = hashCode * 59 + Concessionaire.GetHashCode();
                if (InstallDate != null)
                    hashCode = hashCode * 59 + InstallDate.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(TagInformation left, TagInformation right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(TagInformation left, TagInformation right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
