/*
 * Datamart Customer Relationship Management
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.Runtime.Serialization;
using System.Text;
using System.Text.Json;


namespace Itau.Cl.RF.CustomerRelationshipMgmnt.Bff.API.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class TagInformations : IEquatable<TagInformations>
    {
        /// <summary>
        /// Gets or Sets DateTagInformation
        /// </summary>

        [DataMember(Name = "dateTagInformation")]
        public long? DateTagInformation { get; set; }

        /// <summary>
        /// Gets or Sets Information
        /// </summary>

        [DataMember(Name = "information")]
        public List<TagInformation> Information { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TagInformations {\n");
            sb.Append("  DateTagInformation: ").Append(DateTagInformation).Append("\n");
            sb.Append("  Information: ").Append(Information).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonSerializer.Serialize(this);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((TagInformations)obj);
        }

        /// <summary>
        /// Returns true if TagInformations instances are equal
        /// </summary>
        /// <param name="other">Instance of TagInformations to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TagInformations other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    DateTagInformation == other.DateTagInformation ||
                    DateTagInformation != null &&
                    DateTagInformation.Equals(other.DateTagInformation)
                ) &&
                (
                    Information == other.Information ||
                    Information != null &&
                    Information.SequenceEqual(other.Information)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (DateTagInformation != null)
                    hashCode = hashCode * 59 + DateTagInformation.GetHashCode();
                if (Information != null)
                    hashCode = hashCode * 59 + Information.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(TagInformations left, TagInformations right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(TagInformations left, TagInformations right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
