/*
 * Customer Score Alert
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.Runtime.Serialization;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Itau.Cl.RF.CustomerScoreAlert.API.Dto
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class AlertResp
    {
        /// <summary>
        /// Gets or Sets Bcstatus
        /// </summary>

        [JsonPropertyName("bcstatus")]
        public string Bcstatus { get; set; }

        /// <summary>
        /// Gets or Sets Uuid
        /// </summary>

        [JsonPropertyName("uuid")]
        public string Uuid { get; set; }

        /// <summary>
        /// Gets or Sets CustomerSessionId
        /// </summary>

        [JsonPropertyName("customerSessionId")]
        public string CustomerSessionId { get; set; }

        /// <summary>
        /// Gets or Sets Score
        /// </summary>

        [JsonPropertyName("score")]
        public int Score { get; set; }


        /// <summary>
        /// Gets or Sets Bcscore
        /// </summary>

        [JsonPropertyName("bcscore")]
        public int Bcscore { get; set; }

        /// <summary>
        /// Gets or Sets PolicyAction
        /// </summary>

        [JsonPropertyName("policyAction")]
        public string PolicyAction { get; set; }

        /// <summary>
        /// Gets or Sets PolicyId
        /// </summary>

        [JsonPropertyName("policyId")]
        public int PolicyId { get; set; }

        /// <summary>
        /// Gets or Sets PolicyName
        /// </summary>

        [JsonPropertyName("policyName")]
        public string PolicyName { get; set; }

        /// <summary>
        /// Gets or Sets AuthFactor
        /// </summary>

        [JsonPropertyName("authFactor")]
        public string AuthFactor { get; set; }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonSerializer.Serialize(this);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((AlertResp)obj);
        }

  



        #region Operators
#pragma warning disable 1591

        public static bool operator ==(AlertResp left, AlertResp right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(AlertResp left, AlertResp right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
