/*
 * Customer Score Alert
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.Runtime.Serialization;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Itau.Cl.RF.CustomerScoreAlert.API.Dto
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class AlertRq
    {
        /// <summary>
        /// Gets or Sets CustomerSessionId
        /// </summary>

        [JsonPropertyName("customerSessionId")]
        public string CustomerSessionId { get; set; }

        /// <summary>
        /// Gets or Sets Uuid
        /// </summary>

        [JsonPropertyName("uuid")]
        public string Uuid { get; set; }

        /// <summary>
        /// Gets or Sets ActivityType
        /// </summary>

        [JsonPropertyName("activityType")]
        public string ActivityType { get; set; }

        /// <summary>
        /// Gets or Sets Brand
        /// </summary>

        [JsonPropertyName("brand")]
        public string Brand { get; set; }

        /// <summary>
        /// Gets or Sets Ip
        /// </summary>

        [JsonPropertyName("ip")]
        public string Ip { get; set; }

        /// <summary>
        /// Gets or Sets UserRut
        /// </summary>

        [JsonPropertyName("userRut")]
        public string UserRut { get; set; }

        /// <summary>
        /// Gets or Sets Solution
        /// </summary>

        [JsonPropertyName("solution")]
        public string Solution { get; set; }


        /// <summary>
        /// Gets or Sets PlatformType
        /// </summary>

        [JsonPropertyName("platformType")]
        public string PlatformType { get; set; }


        /// <summary>
        /// Gets or Sets UserAgent
        /// </summary>

        [JsonPropertyName("userAgent")]
        public string UserAgent { get; set; }

        /// <summary>
        /// Gets or Sets AuthMethodUsed
        /// </summary>

        [JsonPropertyName("authMethodUsed")]
        public string AuthMethodUsed { get; set; }


        /// <summary>
        /// Gets or Sets BiometricLogin
        /// </summary>

        [JsonPropertyName("biometricLogin")]
        public bool BiometricLogin { get; set; }


        /// <summary>
        /// Gets or Sets NumOfFailedAuth
        /// </summary>

        [JsonPropertyName("numOfFailedAuth")]
        public int NumOfFailedAuth { get; set; }


        /// <summary>
        /// Gets or Sets YearOfBirth
        /// </summary>

        [JsonPropertyName("yearOfBirth")]
        public int YearOfBirth { get; set; }


        /// <summary>
        /// Gets or Sets AccountBalance
        /// </summary>

        [JsonPropertyName("accountBalance")]
        public int AccountBalance { get; set; }


        /// <summary>
        /// Gets or Sets AccountOpendate
        /// </summary>

        [JsonPropertyName("accountOpendate")]
        public string AccountOpendate { get; set; }


        /// <summary>
        /// Gets or Sets PasswordChangeDate
        /// </summary>

        [JsonPropertyName("passwordChangeDate")]
        public string PasswordChangeDate { get; set; }

        /// <summary>
        /// Gets or Sets ThirdPartyFlow
        /// </summary>

        [JsonPropertyName("thirdPartyFlow")]
        public string ThirdPartyFlow { get; set; }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonSerializer.Serialize(this);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((AlertRq)obj);
        }

  



        #region Operators
#pragma warning disable 1591

        public static bool operator ==(AlertRq left, AlertRq right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(AlertRq left, AlertRq right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
