/*
 * Datamart Customer Relationship Management
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.Runtime.Serialization;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Itau.Cl.RF.CustomerScoreAlert.Domain.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class AuthFactor
    {
        /// <summary>
        /// Gets or Sets UserRut
        /// </summary>

        [JsonPropertyName( "userRut")]
        public string UserRut { get; set; }

        /// <summary>
        /// Gets or Sets UserGroup
        /// </summary>

        [JsonPropertyName( "userGroup")]
        public string UserGroup { get; set; }

        /// <summary>
        /// Gets or Sets UserTypeID
        /// </summary>

        [JsonPropertyName( "userTypeID")]
        public string UserTypeID { get; set; }

        /// <summary>
        /// Gets or Sets FATypeID
        /// </summary>

        [JsonPropertyName( "FATypeID")]
        public string FATypeID { get; set; }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonSerializer.Serialize(this);
        }

    }
}
