/*
 * Datamart Customer Relationship Management
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.Runtime.Serialization;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Itau.Cl.RF.CustomerScoreAlert.Domain.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class AuthFactorItem
    {
        /// <summary>
        /// Gets or Sets FAID
        /// </summary>

        [JsonPropertyName("fAID")]
        public string FAID { get; set; }

        /// <summary>
        /// Gets or Sets FATypeID
        /// </summary>

        [JsonPropertyName("fATypeID")]
        public string FATypeID { get; set; }

        /// <summary>
        /// Gets or Sets FATypeDesc
        /// </summary>

        [JsonPropertyName("fATypeDesc")]
        public string FATypeDesc { get; set; }


        /// <summary>
        /// Gets or Sets userTypeID
        /// </summary>

        [JsonPropertyName("userTypeID")]
        public string userTypeID { get; set; }

        /// <summary>
        /// Gets or Sets userTypeDesc
        /// </summary>

        [JsonPropertyName("userTypeDesc")]
        public string userTypeDesc { get; set; }

        /// <summary>
        /// Gets or Sets FAState
        /// </summary>

        [JsonPropertyName("fAState")]
        public string FAState { get; set; }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonSerializer.Serialize(this);
        }

    }
}
