/*
 * Datamart Customer Relationship Management
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.Runtime.Serialization;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Itau.Cl.RF.CustomerScoreAlert.Domain.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class BiometricScore
    {
        /// <summary>
        /// Gets or Sets CustomerSessionId
        /// </summary>

        [JsonPropertyName("customerSessionID")]
        public string CustomerSessionId { get; set; }

        /// <summary>
        /// Gets or Sets Uuid
        /// </summary>

        [JsonPropertyName("uuid")]
        public string Uuid { get; set; }

        /// <summary>
        /// Gets or Sets ActivityType
        /// </summary>

        [JsonPropertyName("activityType")]
        public string ActivityType { get; set; }

        /// <summary>
        /// Gets or Sets Brand
        /// </summary>

        [JsonPropertyName("brand")]
        public string Brand { get; set; }

        /// <summary>
        /// Gets or Sets Ip
        /// </summary>

        [JsonPropertyName("ip")]
        public string Ip { get; set; }


        /// <summary>
        /// Gets or Sets Solution
        /// </summary>

        [JsonPropertyName("solution")]
        public string Solution { get; set; }


        /// <summary>
        /// Gets or Sets PlatformType
        /// </summary>

        [JsonPropertyName("platformType")]
        public string PlatformType { get; set; }


        /// <summary>
        /// Gets or Sets UserAgent
        /// </summary>

        [JsonPropertyName("userAgent")]
        public string UserAgent { get; set; }

        /// <summary>
        /// Gets or Sets AuthMethodUsed
        /// </summary>

        [JsonPropertyName("authMethodUsed")]
        public string AuthMethodUsed { get; set; }


        /// <summary>
        /// Gets or Sets BiometricLogin
        /// </summary>

        [JsonPropertyName("biometricLogin")]
        public bool BiometricLogin { get; set; }


        /// <summary>
        /// Gets or Sets NumOfFailedAuth
        /// </summary>

        [JsonPropertyName("numOfFailedAuth")]
        public int NumOfFailedAuth { get; set; }


        /// <summary>
        /// Gets or Sets YearOfBirth
        /// </summary>

        [JsonPropertyName("yearOfBirth")]
        public int YearOfBirth { get; set; }


        /// <summary>
        /// Gets or Sets AccountBalance
        /// </summary>

        [JsonPropertyName("accountBalance")]
        public int AccountBalance { get; set; }


        /// <summary>
        /// Gets or Sets AccountOpendate
        /// </summary>

        [JsonPropertyName("accountOpendate")]
        public string AccountOpendate { get; set; }


        /// <summary>
        /// Gets or Sets PasswordChangeDate
        /// </summary>

        [JsonPropertyName("passwordChangeDate")]
        public string PasswordChangeDate { get; set; }

        /// <summary>
        /// Gets or Sets ThirdPartyFlow
        /// </summary>

        [JsonPropertyName("thirdPartyFlow")]
        public string ThirdPartyFlow { get; set; }

        /// <summary>
        /// Gets or Sets RecurrentPayee
        /// </summary>

        [JsonPropertyName("recurrentPayee")]
        public bool RecurrentPayee { get; set; }

        /// <summary>
        /// Gets or Sets ActivityAmount
        /// </summary>

        [JsonPropertyName("activityAmount")]
        public string ActivityAmount { get; set; }

        /// <summary>
        /// Gets or Sets ActivityName
        /// </summary>

        [JsonPropertyName("activityName")]
        public string ActivityName { get; set; }


        /// <summary>
        /// Gets or Sets Market
        /// </summary>

        [JsonPropertyName("market")]
        public string Market { get; set; }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonSerializer.Serialize(this);
        }

    }
}
