/*
 * Datamart Customer Relationship Management
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.Runtime.Serialization;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Itau.Cl.RF.CustomerScoreAlert.Domain.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class BlockStatusItem
    {
        /// <summary>
        /// Gets or Sets FatypeId
        /// </summary>

        [JsonPropertyName("fatypeId")]
        public string FatypeId { get; set; }

        /// <summary>
        /// Gets or Sets FaTypeDesc
        /// </summary>

        [JsonPropertyName("faTypeDesc")]
        public string FaTypeDesc { get; set; }

        /// <summary>
        /// Gets or Sets FaId
        /// </summary>

        [JsonPropertyName("faId")]
        public string FaId { get; set; }


        /// <summary>
        /// Gets or Sets Block
        /// </summary>

        [JsonPropertyName("block")]
        public string Block { get; set; }

        /// <summary>
        /// Gets or Sets ErrorCode
        /// </summary>

        [JsonPropertyName("errorCode")]
        public string ErrorCode { get; set; }

        /// <summary>
        /// Gets or Sets InternalCode
        /// </summary>

        [JsonPropertyName("internalCode")]
        public string InternalCode { get; set; }

        /// <summary>
        /// Gets or Sets ErrorMessage
        /// </summary>

        [JsonPropertyName("errorMessage")]
        public string ErrorMessage { get; set; }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonSerializer.Serialize(this);
        }

    }
}
