/*
 * Datamart Customer Relationship Management
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.Runtime.Serialization;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Itau.Cl.RF.CustomerScoreAlert.Domain.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class ScoreStatus
    {
        /// <summary>
        /// Gets or Sets Bcstatus
        /// </summary>

        [JsonPropertyName("bcstatus")]
        public string Bcstatus { get; set; }

        /// <summary>
        /// Gets or Sets Uuid
        /// </summary>

        [JsonPropertyName("uuid")]
        public string Uuid { get; set; }

        /// <summary>
        /// Gets or Sets ErrorDescription
        /// </summary>

        [JsonPropertyName("errorDescription")]
        public string ErrorDescription { get; set; }

        /// <summary>
        /// Gets or Sets CustomerSessionId
        /// </summary>

        [JsonPropertyName("customerSessionID")]
        public string CustomerSessionId { get; set; }

        /// <summary>
        /// Gets or Sets Score
        /// </summary>

        [JsonPropertyName("score")]
        public int Score { get; set; }

        /// <summary>
        /// Gets or Sets BcScore
        /// </summary>

        [JsonPropertyName("bcScore")]
        public int BcScore { get; set; }


        /// <summary>
        /// Gets or Sets PolicyAction
        /// </summary>

        [JsonPropertyName("policyAction")]
        public string PolicyAction { get; set; }


        /// <summary>
        /// Gets or Sets PolicyId
        /// </summary>

        [JsonPropertyName("policyId")]
        public int PolicyId { get; set; }


        /// <summary>
        /// Gets or Sets PolicyName
        /// </summary>

        [JsonPropertyName("policyName")]
        public string PolicyName { get; set; }

        /// <summary>
        /// Gets or Sets IsBot
        /// </summary>

        [JsonPropertyName("isBot")]
        public bool IsBot { get; set; }


        /// <summary>
        /// Gets or Sets IsEmulator
        /// </summary>

        [JsonPropertyName("isEmulator")]
        public bool IsEmulator { get; set; }


        /// <summary>
        /// Gets or Sets IsRat
        /// </summary>

        [JsonPropertyName("isRat")]
        public bool IsRat { get; set; }


        /// <summary>
        /// Gets or Sets IsRecentRat
        /// </summary>

        [JsonPropertyName("isRecentRat")]
        public bool IsRecentRat { get; set; }


        /// <summary>
        /// Gets or Sets IsMobileRat
        /// </summary>

        [JsonPropertyName("isMobileRat")]
        public bool IsMobileRat { get; set; }


        /// <summary>
        /// Gets or Sets StatusCode
        /// </summary>

        [JsonPropertyName("statusCode")]
        public int StatusCode { get; set; }

        /// <summary>
        /// Gets or Sets ReasonPhrase
        /// </summary>

        [JsonPropertyName("reasonPhrase")]
        public string ReasonPhrase { get; set; }


        /// <summary>
        /// Gets or Sets IsSuccessStatusCode
        /// </summary>

        [JsonPropertyName("isSuccessStatusCode")]
        public bool IsSuccessStatusCode { get; set; }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonSerializer.Serialize(this);
        }
    }
}
