/*
 * Datamart Customer Relationship Management
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.Runtime.Serialization;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Itau.Cl.RF.CustomerScoreAlert.Domain.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class SendNotification
    {
        /// <summary>
        /// Gets or Sets Priority
        /// </summary>

        [JsonPropertyName("priority")]
        public string Priority { get; set; }

        /// <summary>
        /// Gets or Sets TemplateId
        /// </summary>

        [JsonPropertyName("templateId")]
        public string TemplateId { get; set; }

        /// <summary>
        /// Gets or Sets GetMailResponse
        /// </summary>

        [JsonPropertyName("getMailResponse")]
        public bool GetMailResponse { get; set; }

        /// <summary>
        /// Gets or Sets ClientId
        /// </summary>

        [JsonPropertyName("clientId")]
        public string ClientId { get; set; }


        /// <summary>
        /// Gets or Sets DocumentType
        /// </summary>

        [JsonPropertyName("documentType")]
        public string DocumentType { get; set; }


        /// <summary>
        /// Gets or Sets Subject
        /// </summary>

        [JsonPropertyName("subject")]
        public string Subject { get; set; }

        /// <summary>
        /// Gets or Sets NoteUse
        /// </summary>

        [JsonPropertyName("noteUse")]
        public string NoteUse { get; set; }

        /// <summary>
        /// Gets or Sets From
        /// </summary>

        [JsonPropertyName("from")]
        public string From { get; set; }

        /// <summary>
        /// Gets or Sets To
        /// </summary>

        [JsonPropertyName("to")]
        public string To { get; set; }

        /// <summary>
        /// Gets or Sets Cc
        /// </summary>

        [JsonPropertyName("cc")]
        public string Cc { get; set; }


        /// <summary>
        /// Gets or Sets Cco
        /// </summary>

        [JsonPropertyName("cco")]
        public string Cco { get; set; }


        /// <summary>
        /// Gets or Sets Listparams
        /// </summary>

        [JsonPropertyName("listparams")]
        public ListParamsItem[] Listparams { get; set; }

        /// <summary>
        /// Gets or Sets Listparams
        /// </summary>

        [JsonPropertyName("attachments")]
        public AttachmentsItem[] Attachments { get; set; }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonSerializer.Serialize(this);
        }

    }
}
